Repository sopra-fs22-group-36/screw-your-neighbor-server, pull requests merged in 2022-04, with the labels that each got.

#96 Feature add self link in auth controller
  src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/controller/AuthController.java
  src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/AuthControllerIntegrationTest.java
Labels: task

#104 hand: add property announcedScore
  doc/m2/uml/activity_requests_diagram.puml
  doc/m2/uml/class_diagram.puml
  src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/Hand.java
  src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/HandEmbedProjection.java
  src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/ScoreAnnouncement.java
  src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/repository/HandRepository.java
  src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/repository/ScoreAnnouncementRepository.java
  src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/GameIntegrationTest.java
Labels: backend, task

#105 Evaluate trick winner
  src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/Round.java
  src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/RoundEmbedProjection.java
  src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/RoundTest.java
Labels: backend, task

#136 shuffle deck before distributing cards
  src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/CardDeck.java
  src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/StandardCardDeck.java
  src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/sideeffects/CardEventHandler.java
  src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/sideeffects/GameEventHandler.java
Labels: backend

#141 Bugfix fix npe for last card of last match
  src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/sideeffects/CardEventHandler.java
  src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/CardEventHandlerTest.java
Labels: backend, task
